# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sokuseki' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
   
  # Pods for Sokuseki
  pod 'Firebase/Auth'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  
  target 'SokusekiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SokusekiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
